### ISSUE TITLE
Addition: VirtualDom Implementation

### ISSUE THREAD

**Issue by mrvicadai** [AlexanderEllis/js-reading-list#1]
Stumbled across this article and I think this is a great resource for the `short` section.

https://medium.com/@deathmood/how-to-write-your-own-virtual-dom-ee74acc13060

Cheers

**Comment by AlexanderEllis** [comment]
Thanks for taking a look, and thanks for the recommendation!  

I think it's very valuable to have an example of a larger codebase (like React's Virtual DOM) that's more approachable.  It's a little more helpful to see how these things are done in existing libraries, so I'm not sure that this exact tutorial is the best fit.  That being said, I had heard about a similar project named [Preact](https://github.com/developit/preact), which is essentially a similarly simplified form of React.  It's a great call to have a more approachable example, so I went ahead and added that in.  Thanks again for the suggestion!
